[package]
name = "rustomata"
version = "0.1.0"
authors = ["Tobias Denkinger <tobias.denkinger@tu-dresden.de>"]

[dependencies]
ordered-float = { git = "https://github.com/tud-fop/rust-ordered-float.git" }
num-traits = "0.1.36"
