[package]
name = "rustomata"
version = "0.1.0"
authors = ["Tobias Denkinger <tobias.denkinger@tu-dresden.de>"]

[dependencies]
clap = "2.19"
integeriser = { git = "https://github.com/tud-fop/rust-integeriser.git" }
log_domain = { git = "https://github.com/tud-fop/rust-log-domain.git" }
nom = "^2.2"
num-traits = "0.1.41"
rand = "0.3.16"
time = "0.1.38"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9"
fnv = "1.0"

[profile.release]
debug = true